### ISSUE TITLE
Old LiveFront code

### ISSUE THREAD

**Issue by Koch** [gathering/wannabe#1]
We found some old LiveFront-related (possibly?) code from 2012:

https://github.com/gathering/wannabe/blob/1838ac98387183837ba274093a2e9715e90a5b23/app/webroot/api/front-login.php#L16-L28

No idea if it is used or not. Possibly something we could look into? PR coming soon to get rid of it

**Comment by Koch** [comment]
PR in #2

**Comment by KristianLyng** [comment]
For the record: All references to Live Front can and should be removed. It is the old system used for managing the gathering.org frontpage (exclusively the frontpage) and is now unused.
