### ISSUE TITLE
Geocode error on frontpage

### ISSUE THREAD

**Issue by Brekkjern** [gathering/wannabe#16]
Error shown on dashboard pages.

`Feil: Geocode was not successful for the following reason: REQUEST_DENIED`

Example:
![image](https://user-images.githubusercontent.com/599405/63349961-c752a300-c35c-11e9-984f-1e35df939c5a.png)

Observed to happen on the following URLs:
https://wannabe.gathering.org/tg18/
https://wannabe.gathering.org/tg19/

Does not happen on https://wannabe.gathering.org/tg20/

**Comment by Koch** [comment]
https://github.com/gathering/wannabe/pull/2/files#diff-228f3643569f6ec2a2cfe47e0c52c6bc

**Comment by Brekkjern** [comment]
Yeah. That seems to be the origin of the issue.

https://github.com/gathering/wannabe/blob/1dc59e837f6b27ea604382bc8f68ba945e81f026/app/View/Home/index.ctp#L224

That line is where the API key is being used and consequently why we are getting our request denied.

**Comment by Brekkjern** [comment]
This should be fairly simple for a beginner to solve. We need the API key to be loaded from a config file somewhere when it's needed.

**Comment by niccofyren** [comment]
Created a PR for this. Mostly just to go through the paces of getting the development environment up and running locally, so feel free to propose better solutions.
