### ISSUE TITLE
Replace vendors with Composer-based dependencies

### ISSUE THREAD

**Issue by simenandre** [gathering/wannabe#21]
I guess that previously, the `/vendors` folder has been used for packages (e.g. dependencies). I suggest that we replace these with packages that are maintained instead.

If we are lucky, it shouldn't be a lot of hassle.

**Comment by niccofyren** [comment]
Fixed by: https://github.com/gathering/wannabe/pull/23

Might need additional tweaks for prettier diffs and 7.3 compatibility later.
