### ISSUE TITLE
Fix error message placement in "create user" workflow

### ISSUE THREAD

**Issue by mkberntsen** [gathering/wannabe#28]
If you try to create a user by entering an email which is already associated with a previous user, an error message is displayed - in the wrong place.
Error message should show in the dialogue to enter the address, but is shown in the wannabe login page, 'behind' the dialogue.

#### Step 1:
Click "create user" and enter email address for existing user. Hit 'create' and observe nothing seems to happen. 
![image](https://user-images.githubusercontent.com/9872537/63552189-51566380-c537-11e9-824c-64474658c70f.png)

#### Step 2:
Exit the dialogue.

#### Step 3:
A magical error message has appeared! The link in the error message takes me to... the login page I'm already on? 
![image](https://user-images.githubusercontent.com/9872537/63552281-8fec1e00-c537-11e9-8723-b424a9c37c36.png)

**Comment by niccofyren** [comment]
Think this might already have a fix on its way in this PR: https://github.com/gathering/wannabe/pull/24 this line https://github.com/gathering/wannabe/blob/246c45c2328b39ec513457c2d387f4d0c9d87af2/app/View/Layouts/front-generic.ctp#L47

Did some tweaks to verification logic which included adding a placement for these kinds of messages on the create user / forgot password pages.
