### ISSUE TITLE
Feature request: Option to use gravatar for profile pictures

### ISSUE THREAD

**Issue by theS1LV3R** [gathering/wannabe#73]
Gravatar has an "API" to access profile pictures based on an MD5 hash of an email address, in this format:

```
MD5(TO_LOWERCASE(EMAIL))
```

See https://en.gravatar.com/site/implement/

**Comment by mfyll** [comment]
The most important purpose of the profile pictures in Wannabe is to be able to create ID-cards. This is also why there are strict rules to how a picture should look and a manual picture approval flow afterwards.

I dont think Gravatar fits in this project.
